import {
  Paragraph,
  Table,
  TextRun,
  ImageRun,
  ExternalHyperlink,
  IPropertiesOptions,
  ISectionOptions,
} from 'docx';
import {
  FallthroughConverter,
  IBlockConverter,
  IInlineConverter,
} from './element-converters/types';
import { DocxStyleMapper, DocxStyleMapping } from './docx-style-mapper';
import { DocumentElement, IStylesheet } from 'html-to-document-core';

export type DocxElement =
  | Paragraph
  | Table
  | TextRun
  | ImageRun
  | ExternalHyperlink;

export type OptionalDocumentOptions = Omit<
  Partial<IPropertiesOptions>,
  'sections'
>;

export type DocxAdapterConfig = {
  blockConverters?: IBlockConverter[];
  inlineConverters?: IInlineConverter[];
  fallthroughConverters?: FallthroughConverter[];
  defaultSectionOptions?: Partial<ISectionOptions>;
  styleMapper?: DocxStyleMapper;
  styleMappings?: DocxStyleMapping;
  /**
   * Optional hook to modify the final document options just before the `docx` `Document` is
   * constructed. Use this hook to inject or override any `IPropertiesOptions` fields that the
   * adapter does not expose directly — for example custom paragraph styles, additional numbering
   * configurations, or document-level settings.
   *
   * The function receives the fully resolved `docxDocumentOptions` (including the default
   * `unordered`/`ordered` numbering configs and the converted `sections`) and must return a valid
   * `IPropertiesOptions` object that will be passed directly to the `docx` `Document` constructor.
   *
   * @example Setting paragraph styles
   * ```ts
   * new DocxAdapter({}, {
   *   beforeConvert: ({ docxDocumentOptions }) => ({
   *     ...docxDocumentOptions,
   *     styles: {
   *       paragraphStyles: [{
   *         id: 'MyStyle',
   *         name: 'My Style',
   *         basedOn: 'Normal',
   *         run: { bold: true },
   *       }],
   *     },
   *   }),
   * });
   * ```
   *
   * @example Replacing the default numbering
   * ```ts
   * new DocxAdapter({}, {
   *   beforeConvert: ({ docxDocumentOptions }) => ({
   *     ...docxDocumentOptions,
   *     numbering: {
   *       config: [{
   *         reference: 'my-list',
   *         levels: [{ level: 0, format: NumberFormat.UPPER_ROMAN, text: '%1.', alignment: AlignmentType.LEFT }],
   *       }],
   *     },
   *   }),
   * });
   * ```
   *
   * @example Extending the default numbering (preserving built-in ordered/unordered configs)
   * ```ts
   * new DocxAdapter({}, {
   *   beforeConvert: ({ docxDocumentOptions }) => ({
   *     ...docxDocumentOptions,
   *     numbering: {
   *       ...docxDocumentOptions.numbering,
   *       config: [
   *         ...(docxDocumentOptions.numbering?.config ?? []),
   *         {
   *           reference: 'extra-list',
   *           levels: [{ level: 0, format: NumberFormat.LOWER_LETTER, text: '%1)', alignment: AlignmentType.LEFT }],
   *         },
   *       ],
   *     },
   *   }),
   * });
   * ```
   */
  beforeConvert?: (data: {
    elements: DocumentElement[];
    stylesheet?: IStylesheet;
    /** The default document options generated by the adapter, before applying this hook. */
    docxDocumentOptions: IPropertiesOptions;
  }) => IPropertiesOptions;
  /**
   * Document options to pass to the docx Document constructor (from `docx`).
   * Can either be an object that overrides the default options, or a function that takes the default options and returns the modified options.
   */
  documentOptions?:
    | OptionalDocumentOptions
    | ((defaultOptions: OptionalDocumentOptions) => OptionalDocumentOptions);
};
