name: Deploy Docs
on:
  push:
    branches: [main]
    paths: ['docs/**', 'package.json']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: {node-version: '20', cache: 'npm'}
      - run: npm ci --prefix docs
      - run: npm run build --prefix docs      # outputs docs/build
      - run: npx vercel deploy --prod --yes --cwd docs --token ${{ secrets.VERCEL_TOKEN }}