name: Release & Publish (monorepo)
on:
  push:
    tags:
      - 'v*.*.*' # e.g. v0.2.0

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies (all workspaces)
        run: npm install

      - name: Build all workspaces
        run: npm run build

      # Publish core first
      - name: Publish html-to-document-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --workspace packages/core --access public --provenance

      # Publish default DOCX adapter
      - name: Publish html-to-document-adapter-docx
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --workspace packages/adapters/docx --access public --provenance

      # Publish default PDF adapter
      - name: Publish html-to-document-adapter-pdf
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --workspace packages/adapters/pdf --access public --provenance

      # Publish wrapper last
      - name: Publish html-to-document (wrapper)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --workspace packages/html-to-document --access public --provenance
